name: Catherine Workflow

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  test_and_build:
    name: Testing Catherine
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo test --verbose
    
    name: Building Catherine
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose
